# Upstream block pointing to the Django Gunicorn container service
upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    # Forward all incoming traffic to the Gunicorn upstream app
    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /metrics {
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;
        allow 127.0.0.1;
        deny all;

        proxy_pass http://web:8000;
    }
}